
CREATE TABLE DIM_FECHA (
                SK_FECHA DATE NOT NULL,
                DIA INTEGER NOT NULL,
                ANIO INTEGER NOT NULL,
                FECHA DATE NOT NULL,
                MES INTEGER NOT NULL,
                CONSTRAINT dim_fecha_pk PRIMARY KEY (SK_FECHA)
);


CREATE TABLE DIM_TEST (
                SK_TEST INTEGER NOT NULL,
                TEST_REALIZADO INTEGER NOT NULL,
                AISLAMIENTO INTEGER NOT NULL,
                TEST_POSITIVO INTEGER NOT NULL,
                VALIDO_DESDE VARCHAR(10) NOT NULL,
                VERSION VARCHAR(10) NOT NULL,
                VALIDO_HASTA VARCHAR(10) NOT NULL,
                CONSTRAINT dim_test_pk PRIMARY KEY (SK_TEST)
);


CREATE TABLE DIM_CATEGORIA (
                SK_CATEGORIA INTEGER NOT NULL,
                NOMBRE_CATEGORIA VARCHAR(50) NOT NULL,
                VERSION VARCHAR(10) NOT NULL,
                VALIDO_HASTA VARCHAR(10) NOT NULL,
                ALTA INTEGER NOT NULL,
                VALIDO_DESDE VARCHAR(10) NOT NULL,
                CONSTRAINT dim_categoria_pk PRIMARY KEY (SK_CATEGORIA)
);


CREATE TABLE DIM_PROVINCIA (
                SK_CODIGO_INE INTEGER NOT NULL,
                NOMBRE_PROVINCIA VARCHAR(50) NOT NULL,
                VALIDO_DESDE VARCHAR(10) NOT NULL,
                VALIDO_DESDE VARCHAR(10) NOT NULL,
                AMBITO VARCHAR(50) NOT NULL,
                VERSION VARCHAR(10) NOT NULL,
                CONSTRAINT dim_provincia_pk PRIMARY KEY (SK_CODIGO_INE)
);


CREATE TABLE RESULTADO (
                SK_TEST INTEGER NOT NULL,
                SK_FECHA DATE NOT NULL,
                SK_CODIGO_INE INTEGER NOT NULL,
                SK_CATEGORIA INTEGER NOT NULL,
                CONSTRAINT resultado_pk PRIMARY KEY (SK_TEST, SK_FECHA, SK_CODIGO_INE, SK_CATEGORIA)
);


ALTER TABLE RESULTADO ADD CONSTRAINT dim_fecha_resultado_fk
FOREIGN KEY (SK_FECHA)
REFERENCES DIM_FECHA (SK_FECHA)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE RESULTADO ADD CONSTRAINT dim_test_resultado_fk
FOREIGN KEY (SK_TEST)
REFERENCES DIM_TEST (SK_TEST)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE RESULTADO ADD CONSTRAINT dim_categoria_resultado_fk
FOREIGN KEY (SK_CATEGORIA)
REFERENCES DIM_CATEGORIA (SK_CATEGORIA)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE RESULTADO ADD CONSTRAINT dim_provincia_resultado_fk
FOREIGN KEY (SK_CODIGO_INE)
REFERENCES DIM_PROVINCIA (SK_CODIGO_INE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
